# =============================================================================
# Magikeys — Makefile
# =============================================================================

PROJECT   := Magikeys.xcodeproj
SCHEME    := Magikeys
BUILD_DIR := build

# Local package reference UUID (deterministic — generated by XcodeGen from project.yml)
PKG_REF_UUID := C9F4A7C64EE4F53F0F15D17D

# Detect xcbeautify for prettier xcodebuild output; fall back to cat
XCBEAUTIFY := $(shell command -v xcbeautify 2>/dev/null)
PRETTY     := $(if $(XCBEAUTIFY), | xcbeautify,)

# Re-export PATH so brew-installed tools are found when invoked via Xcode run scripts
export PATH := /opt/homebrew/bin:/usr/local/bin:$(PATH)

.DEFAULT_GOAL := help

.PHONY: help setup gen open \
        build release \
        test uitest test-all \
        format lint \
        archive \
        clean reset \
        ci

# -----------------------------------------------------------------------------
# Help
# -----------------------------------------------------------------------------

help: ## Show available targets
	@echo ""
	@echo "  Magikeys"
	@echo ""
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
	    | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-14s\033[0m %s\n", $$1, $$2}'
	@echo ""

# -----------------------------------------------------------------------------
# Setup
# -----------------------------------------------------------------------------

setup: ## Install required tools and generate Xcode project
	@echo "→ Checking tools..."
	@command -v xcodegen   >/dev/null || (echo "  Installing xcodegen..."   && brew install xcodegen)
	@command -v swift-format >/dev/null || (echo "  Installing swift-format..." && brew install swift-format)
	@command -v xcbeautify >/dev/null || (echo "  Installing xcbeautify..." && brew install xcbeautify)
	@echo "  ✓ xcodegen   $$(xcodegen version)"
	@echo "  ✓ swift-format $$(swift-format --version 2>&1)"
	@echo "  ✓ xcbeautify $$(xcbeautify --version 2>&1)"
	@echo ""
	@$(MAKE) gen

# -----------------------------------------------------------------------------
# Project generation
# -----------------------------------------------------------------------------

# XcodeGen 2.x omits the required `package` back-reference in
# XCSwiftPackageProductDependency for local packages — patch it after every
# generate so Xcode can resolve MagikeysKit.
_patch-pbxproj:
	@perl -i -p0e \
	    's/(isa = XCSwiftPackageProductDependency;\n)(\t+productName = MagikeysKit;)/$$1\t\t\tpackage = $(PKG_REF_UUID) \/* XCLocalSwiftPackageReference "." *\/;\n$$2/' \
	    $(PROJECT)/project.pbxproj
	@echo "  ✓ patched XCSwiftPackageProductDependency"

gen: ## Regenerate Xcode project from project.yml (run after editing project.yml)
	@echo "→ Generating Xcode project..."
	xcodegen generate
	@$(MAKE) --no-print-directory _patch-pbxproj

open: gen ## Regenerate and open project in Xcode
	open $(PROJECT)

# -----------------------------------------------------------------------------
# Build
# -----------------------------------------------------------------------------

build: ## Build app — Debug (via xcodebuild)
	@echo "→ Building (Debug)..."
	xcodebuild build \
	    -project $(PROJECT) \
	    -scheme  $(SCHEME) \
	    -configuration Debug \
	    -derivedDataPath $(BUILD_DIR) \
	    ONLY_ACTIVE_ARCH=YES \
	    $(PRETTY)

release: ## Build app — Release (via xcodebuild)
	@echo "→ Building (Release)..."
	xcodebuild build \
	    -project $(PROJECT) \
	    -scheme  $(SCHEME) \
	    -configuration Release \
	    -derivedDataPath $(BUILD_DIR) \
	    $(PRETTY)

# -----------------------------------------------------------------------------
# Tests
# -----------------------------------------------------------------------------

test: ## Run unit tests via swift test (fast, no Xcode needed)
	@echo "→ Running unit tests..."
	swift test --configuration debug

uitest: ## Run UI tests via xcodebuild
	@echo "→ Running UI tests..."
	xcodebuild test \
	    -project $(PROJECT) \
	    -scheme  $(SCHEME) \
	    -only-testing:MagikeysUITests \
	    -derivedDataPath $(BUILD_DIR) \
	    ONLY_ACTIVE_ARCH=YES \
	    $(PRETTY)

test-all: test uitest ## Run all tests (unit + UI)

# -----------------------------------------------------------------------------
# Code quality
# -----------------------------------------------------------------------------

format: ## Auto-format all Swift source files with swift-format
	@echo "→ Formatting..."
	swift-format format --in-place --recursive Sources Tests
	@echo "  ✓ done"

lint: ## Lint Swift source files with swift-format (no writes)
	@echo "→ Linting..."
	swift-format lint --recursive Sources Tests
	@echo "  ✓ done"

# -----------------------------------------------------------------------------
# Archive / Release
# -----------------------------------------------------------------------------

ARCHIVE_PATH := $(BUILD_DIR)/$(SCHEME).xcarchive

archive: ## Create a Release archive (.xcarchive)
	@echo "→ Archiving..."
	xcodebuild archive \
	    -project     $(PROJECT) \
	    -scheme      $(SCHEME) \
	    -configuration Release \
	    -archivePath $(ARCHIVE_PATH) \
	    $(PRETTY)
	@echo "  ✓ archive: $(ARCHIVE_PATH)"

# -----------------------------------------------------------------------------
# Clean
# -----------------------------------------------------------------------------

clean: ## Remove build artifacts (keeps .xcodeproj)
	@echo "→ Cleaning build artifacts..."
	rm -rf $(BUILD_DIR)
	swift package clean
	@echo "  ✓ done"

reset: clean ## Full reset — also removes .xcodeproj (run 'make gen' afterwards)
	@echo "→ Removing generated project..."
	rm -rf $(PROJECT)
	@echo "  ✓ done. Run 'make gen' to regenerate."

# -----------------------------------------------------------------------------
# CI
# -----------------------------------------------------------------------------

ci: ## Full CI pipeline: lint → unit tests → release build
	@echo "========================================="
	@echo "  Magikeys CI Pipeline"
	@echo "========================================="
	@echo ""
	@echo "--- lint ---"
	@$(MAKE) --no-print-directory lint
	@echo ""
	@echo "--- unit tests ---"
	@$(MAKE) --no-print-directory test
	@echo ""
	@echo "--- release build ---"
	@$(MAKE) --no-print-directory release
	@echo ""
	@echo "========================================="
	@echo "  ✓ CI passed"
	@echo "========================================="